name: Summarize PR
description: Summarize the code changes in a pull request using OpenAI API
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  openai_api_key:
    description: 'OpenAI API key'
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
