name: Summarize PR
description: Summarize the code changes in a pull request using OpenAI API
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  openai_api_key:
    description: 'OpenAI API key'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v2
      shell: bash  # Added shell property
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      shell: bash  # Added shell property
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub openai
      shell: bash  # Added shell property
    - name: Run summarize script
      run: python actions/summarize-pr/index.py
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      shell: bash  # Added shell property