name: Summarize PR
description: Summarize the code changes in a pull request using OpenAI API
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  openai_api_key:
    description: 'OpenAI API key'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out a repository with the action
      uses: actions/checkout@v2
      with:
        repository: 'dbatishchev/summarize-pr-action'
        path: 'summarize-pr-action'
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub openai
      shell: bash

    - name: Run summarize script
      run: python summarize-pr-action/actions/summarize-pr/index.py
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      shell: bash